all: build run

build:
	javac -d bin Main.java aulas/Aula20.java libs/*.java
	
run:
	@java -cp bin Main

clear:
	rm bin/Main.class

git:
	git config --global user.email "niciugcruz@gmail.com"
	git config --global user.name "Vinicius Gomes"
