all: build run

build:
	@javac -d bin Main.java aulas/Aula.java libs/*.java
	
run:
	@java -cp bin Main

clear:
	rm -r bin/*

git:
	git config --global user.email "niciugcruz@gmail.com"
	git config --global user.name "Vinicius Gomes"
